package org.example;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
	private WarehouseRepository warehouseRepository;

	@Autowired
	private ProductRepository productRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String email) {

		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@PostMapping(path="/warehouse/add")
	public @ResponseBody String addWarehouse(
			@RequestParam String warehouseName,
			@RequestParam String warehouseAddress,
			@RequestParam String warehouseCity,
			@RequestParam String warehouseCountry) {

		Warehouse warehouse = new Warehouse();

		warehouse.setWarehouseName(warehouseName);
		warehouse.setWarehouseAddress(warehouseAddress);
		warehouse.setWarehouseCity(warehouseCity);
		warehouse.setWarehouseCountry(warehouseCountry);

		warehouseRepository.save(warehouse);

		return "Warehouse saved";
	}

	@GetMapping(path="/warehouse/all")
	public @ResponseBody Iterable<Warehouse> getAllWarehouses() {
		return warehouseRepository.findAll();
	}

	@PostMapping(path="/product/add")
	public @ResponseBody String addProduct(
			@RequestParam String productName,
			@RequestParam String productCategory,
			@RequestParam Integer productQuantity,
			@RequestParam String productUnit,
			@RequestParam Integer warehouseId) {

		Warehouse warehouse = warehouseRepository.findById(warehouseId).orElse(null);

		if (warehouse == null) {
			return "Warehouse not found";
		}

		Product product = new Product();

		product.setProductName(productName);
		product.setProductCategory(productCategory);
		product.setProductQuantity(productQuantity);
		product.setProductUnit(productUnit);
		product.setWarehouse(warehouse);

		productRepository.save(product);

		return "Product saved";
	}

	@GetMapping(path="/product/all")
	public @ResponseBody Iterable<Product> getAllProducts() {
		return productRepository.findAll();
	}
}